homeassistant:
  name: Home
  unit_system: metric
  temperature_unit: C
  time_zone: Australia/Sydney
  currency: AUD
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  packages: !include_dir_named packages
  external_url: !secret homeassistant_external_url 

http:
  port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  # use ui-lovelace.yaml
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: https://fonts.googleapis.com/css?family=Comfortaa&display=swap
      type: css
    - url: /local/style.css
      type: css

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google_translate

# Store sensors data in InfluxDB
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Use MariaDB as storage
recorder:
  db_url: !secret recorder_db_url
  commit_interval: 60

# Withings - weighing machine data
withings:
  client_id: !secret withings_client_id
  client_secret: !secret withings_client_secret
  use_webhook: true
