- platform: time_date
  display_options:
    - time
    - date

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: "/"
    - type: memory_use_percent
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
    - type: network_in
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_out
      arg: eth0

  scan_interval: 120
