title: Home
views:
  - theme: kibibit-dark-cards
    path: default_view
    title: Home
    icon: mdi:greenhouse
    badges: []
    cards:
      # First column
      - type: vertical-stack
        cards:
          - type: markdown
            content: "## &nbsp;"
            theme: tablet
          - type: weather-forecast
            show_forecast: false
            entity: weather.wolli_creek_hourly
            secondary_info_attribute: humidity
          - show_name: false
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: sensor.speedtest_download
              - entity: sensor.speedtest_upload
              - entity: sensor.speedtest_ping
            state_color: false
          - type: glance
            entities:
              - entity: sensor.rpi_cpu
              - entity: sensor.rpi_mem
              - entity: sensor.rpi_sd
          - show_forecast: true
            type: weather-forecast
            entity: weather.wolli_creek
            secondary_info_attribute: humidity

      # Living Room
      - type: vertical-stack
        cards: !include areas/ui-living-room.yaml

      # Study
      - type: vertical-stack
        cards: !include areas/ui-study.yaml

      # Bedroom
      - type: vertical-stack
        cards: !include areas/ui-bedroom.yaml
