title: Home
views:
  - theme: kibibit-dark-cards
    path: default_view
    title: Home
    icon: mdi:greenhouse
    badges: []
    cards:
      # First column
      - type: vertical-stack
        cards:
          - type: weather-forecast
            show_forecast: false
            entity: weather.wolli_creek_hourly
            secondary_info_attribute: humidity
            theme: tablet


          - type: grid
            columns: 2
            square: false
            cards:
              - type: custom:mushroom-entity-card
                entity: sun.sun
                icon_color: amber

              - type: conditional
                conditions:
                  - entity: sensor.hacs
                    state_not: "0"
                card:
                  # https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/entity.md
                  type: custom:mushroom-entity-card
                  name: "HACS"
                  entity: sensor.hacs


          - type: grid
            columns: 2
            square: false
            cards:
              - type: custom:mushroom-entity-card
                entity: sensor.processor_use

              - type: custom:mushroom-entity-card
                entity: sensor.memory_use_percent

              - type: custom:mushroom-entity-card
                entity: sensor.disk_use_percent
                icon_color: teal

              - type: custom:mushroom-entity-card
                entity: sensor.disk_free
                icon_color: teal


          - type: weather-forecast
            show_forecast: true
            entity: weather.wolli_creek
            style: |
              :host .content {
                display: none;
              }

      # Living Room
      - type: vertical-stack
        cards: !include areas/ui-living-room.yaml

      # Study
      - type: vertical-stack
        cards: !include areas/ui-study.yaml

      # Bedroom
      - type: vertical-stack
        cards: !include areas/ui-bedroom.yaml
