title: Home
views:
  - theme: kibibit-dark-cards
    path: default_view
    title: Home
    icon: mdi:greenhouse
    badges: []
    cards:
      # First column
      - type: vertical-stack
        cards:
          - type: weather-forecast
            show_forecast: false
            entity: weather.wolli_creek_hourly
            secondary_info_attribute: humidity
            theme: tablet
          
          - type: glance
            show_name: false
            entities:
              - entity: sensor.speedtest_download
              - entity: sensor.speedtest_upload
              - entity: sensor.speedtest_ping

          - type: glance
            show_name: false
            entities:
              - entity: sensor.processor_use
              - entity: sensor.memory_use_percent
              - entity: sensor.disk_free
          
          - type: weather-forecast
            show_forecast: true
            entity: weather.wolli_creek
            secondary_info_attribute: humidity

      # Living Room
      - type: vertical-stack
        cards: !include areas/ui-living-room.yaml

      # Study
      - type: vertical-stack
        cards: !include areas/ui-study.yaml

      # Bedroom
      - type: vertical-stack
        cards: !include areas/ui-bedroom.yaml
